//KeypadAction
export const ADD_TOKEN = 'ADD_TOKEN'
export const UPDATE_TOKENLIST = 'UPDATE_TOKENLIST'
export const UPDATE_DISPLAY_VALUE = 'UPDATE_DISPLAY_VALUE'
export const UPDATE_CALCHISTORY = 'UPDATE_CALCHISTORY '
export const CLEAR_TOKENLIST = 'CLEAR_TOKENLIST'
export const CLEAR_CALCHISTORY = 'CLEAR_CALCHISTORY'
export const ADD_PERIOD = 'ADD_PERIOD'

//Theme Action
export const CHANGE_THEME = 'CHANGE_THEME'
export const CHANGE_MODE_CALCULATOR =
  'CHANGE_MODE_CALCULATOR'
